name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release --all-targets
    - name: Compress
      run: tar -czf release.tar.gz target/release/luksmount target/release/luksumount
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: release.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: release
    - uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        name: ${{ github.ref }}
        generate_release_notes: true
        files: |
          release.tar.gz
